### ISSUE TITLE
ユーザー一覧ページから直接チャットルームへ遷移できない件について

### ISSUE THREAD

**Issue by iijima-yuri** [iijima-yuri/DANSYARI#109]
お疲れ様です。
面談で相談させていただいた内容と少し変わるのですが、以下の問題が発生しました。
- 片方のユーザーでチャットを打っても、もう片方のユーザーのチャットルームは開始されない
- 新しいチャットルームを作ったあと、ページを離れてもう一度ユーザー一覧ページに来ても、作ったはずの既存のチャットルームに遷移しない
- チャットルームのメッセージの名前がログインしているユーザーの名前と異なってしまう
上記2点はentrance.html.erbのlink_toのchat_room_pathの引数が違うと思っていますが、解決策が見つかりません。

お手数ですが、アドバイスいただけるとありがたいです。
ご面倒おかけいたしますが、よろしくお願いいたします。

- entrance.html.erb
```
<div class="bg-[#f5eace]">
<%= render 'shared/header' %>
  <div>
    <div class="container mx-auto">
      <h1 class="secondary-title"><%= t('.title') %></h1>
      <div class="grid grid-cols-1 gap-10 pb-6 lg:grid-cols-3 md:grid-cols-2 auto-rows-auto place-content-center place-items-center">
          <% if logged_in? %>
            <% @followers.each do |follower| %>
              <% chat_room_ids = Entry.where(chat_room_id: @chat_room_ids, user_id:follower.followed.id).pluck(:chat_room_id) %>
              
              <% unless chat_room_ids == [] %>
              
                <%= link_to chat_room_path(chat_room_ids.first) do %>
                  <%= "#{follower.followed.name}とのチャットを続ける" %>
                <% end %>
              <% else %>
                <%= form_for @chat_room do |f| %>
                  <%= fields_for @entry do |e| %>
                    <%= e.hidden_field :user_id, value: follower.followed.id %>
                    
                  <% end %>
                  <%= f.submit "#{follower.followed.name}とのチャットを開始する", id: "dm_submit" %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>
```
- chat_rooms_controller.rb
```
class ChatRoomsController < ApplicationController
  before_action :require_login

  def entrance
    @followers = current_user.followers
    @current_user_entry = Entry.where(user_id: current_user.id)
    
    @chat_room_ids = []
    
    @followers.each do |follower|
      
      unless follower.id == current_user.id
        @is_chat_room = false
        @user_entry = Entry.where(user_id: follower.id)
        
        @current_user_entry.each do |cu|
          @user_entry.each do |u|
            if cu.chat_room_id == u.chat_room_id
              @is_chat_room = true
              @chat_room_ids << cu.chat_room_id
              @chat_room_id = cu.chat_room_id
            end
          end
        end
        unless @is_chat_room
          @chat_room = ChatRoom.new
          @entry = Entry.new
          @chat_room_ids << @chat_room.id
        end
      end
    end
  end

  def show
    @chat_room = ChatRoom.find(params[:id])
    if Entry.where(user_id: current_user.id, chat_room_id: @chat_room.id).present?
      @messages = @chat_room.messages
      @entries = @chat_room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @chat_room = ChatRoom.create(name: "DM")
    @entry1 = Entry.create(chat_room_id: @chat_room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :chat_room_id).merge(chat_room_id: @chat_room.id))
    redirect_to chat_room_path(@chat_room.id)
  end

  def destroy
    chat_room = ChatRoom.find(params[:id])
    chat_room.destroy
    redirect_to chat_rooms_path
  end
end

```

**Comment by Tsuchiya2** [comment]
> チャットルームのメッセージの名前がログインしているユーザーの名前と異なってしまう

dogでログインしておりますが、ログインしているユーザーの名前と一致しておりますが...これはどういった現象なのでしょうか。
<img width="410" alt="スクリーンショット 2024-01-31 18 47 44" src="https://github.com/iijima-yuri/DANSYARI/assets/61481161/30923ad7-a6e6-4f29-a907-ee732813cfd4">

---

>片方のユーザーでチャットを打っても、もう片方のユーザーのチャットルームは開始されない
新しいチャットルームを作ったあと、ページを離れてもう一度ユーザー一覧ページに来ても、作ったはずの既存のチャットルームに遷移しない

下記動画のとおり、アクセスする度にURLの部分が変わっているのが確認できました。おそらくそれが原因ではないでしょうか。

https://github.com/iijima-yuri/DANSYARI/assets/61481161/939619fa-c88a-491c-8ca9-a72b5a6b2246

---

●エラー共有
以下の動画にあるように操作したところエラー画面が出てしまいました。共有まで。
https://github.com/iijima-yuri/DANSYARI/assets/61481161/d40e33ff-0301-41f7-ad85-990d8076b495

**Comment by iijima-yuri** [comment]
ご返信ありがとうございます。

>>チャットルームのメッセージの名前がログインしているユーザーの名前と異なってしまう
>
>dogでログインしておりますが、ログインしているユーザーの名前と一致しておりますが...これはどういった現象なのでしょうか。

今、操作してみたんですが、もとに戻っていました、、、。
最終的にできたら、もう一回確認します。お手数おかけしました、、、。
[![Image from Gyazo](https://i.gyazo.com/3b15db04c382fa5ce1cdd977036321d5.png)](https://gyazo.com/3b15db04c382fa5ce1cdd977036321d5)



>>片方のユーザーでチャットを打っても、もう片方のユーザーのチャットルームは開始されない
>>新しいチャットルームを作ったあと、ページを離れてもう一度ユーザー一覧ページに来ても、作ったはずの既存のチャットルームに遷移しない
>
>下記動画のとおり、アクセスする度にURLの部分が変わっているのが確認できました。おそらくそれが原因ではないでしょうか。

binding.pryで確認したところ、毎回@chat_roomが作られていて、
chat_rooms_controller.rbの抜粋
```
unless @is_chat_room
          @chat_room = ChatRoom.new
          @entry = Entry.new
          @chat_room_ids << @chat_room.id
```
この部分で@chat_room.idがnilになっており、@chat_room_idsにidを渡せていないことがわかりました。そこで上記のnewをcreateにしてみたところ、@chat_room_idsには値が入ったのですが、以下のコードでchat_room_idsが空になってしまいます。
entrance.html.erbの抜粋
```
<% chat_room_ids = Entry.where(chat_room_id: @chat_room_ids, user_id:follower.followed.id).pluck(:chat_room_id) %>
```
そこで、以下のコードの@entryをbinding.pryしてみたところ、chat_room_idは入っていたのですが、idがnilだったので、user_id:current_user.idを入れたところ、保存ができました。

chat_rooms_controller.rbの抜粋
```
unless @is_chat_room
          @chat_room = ChatRoom.create
          @entry = Entry.create(chat_room_id: @chat_room.id)
          @chat_room_ids << @chat_room.id
        end
```

しかし、依然chat_room_idsが空になっています。
やはり、以下のパスの引数が間違っているのでしょうか。
アドバイスいただけると、とても助かります。
entrance.html.erbの抜粋
```
<% chat_room_ids = Entry.where(chat_room_id: @chat_room_ids, user_id: follower.followed.id ).pluck(:chat_room_id) %>
              <% unless chat_room_ids == [] %>
                <%= link_to chat_room_path(chat_room_ids.first) do %>
```



>●エラー共有
以下の動画にあるように操作したところエラー画面が出てしまいました。共有まで。

共有いただきありがとうございます。消したuserのルーテングのリンクを使っていたことが原因でした。変更しておきます。

**Comment by Tsuchiya2** [comment]
手元にコードが無いので正しく挙動するかは分かりませんが...
以下、Railsっぽい書き方から離れますが、ロジック的にはAさんとBさんが共通して鼠族しているChatRoomを探し出せるかと思うので、ロジック部分確認＆自分のコードに噛み砕き理解して修正してみてください。

- フォローした時点でChatRoomを1つ作成、作成したChatRoomを元にEntryを2つ作成
- entranceページではフォローしている人を一覧で表示
- ↑のページでchat_room#showへのリンクを設けて、pathの引数にはフォローしているユーザーのオブジェクトを渡す
- chat_room#showアクションでログインしているユーザーが持っているchat_roomのidsを取得（A）
- chat_room#showのparams[:id]を使って、フォローしている人が持っているchat_roomのidsを取得（B）
- AとBが重なるChatRoomのidを探し出す
- 重なった↑のidを元にChatRoom.find(重なったid)で対象のChatRoomレコードを取得してビューで表示

```ruby
# ChatRoomsController
def entrance
  @followers = current_user.followers
end

def show
  target_user_have_chat_room_ids = Entry.where(user_id: param[:id]).pluck(:chat_room_id)
  current_user_have_chat_room_ids = Entry.where(user_id: current_user.id).pluck(:chat_room_id)
  target_chat_room_id = (target_user_have_chat_room_ids & current_user_have_chat_room_ids)
  @chat_room = ChatRoom.find(target_chat_room_id)
  ....
end
```

```erb
# entrance.html.erb
<div class="grid grid-cols-1 gap-10 pb-6 lg:grid-cols-3 md:grid-cols-2 auto-rows-auto place-content-center place-items-center">
    <% if logged_in? %>
      <% @followers.each do |follower| %>
        <%= link_to chat_room_path(follower) do %>
          <%= "#{follower.followed.name}とのチャット" %>
        <% end %>
      <% end %>
    <% end %>
</div>
```

```ruby
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    ActiveRecord::Base.transaction do
      chat_room = ChatRoom.create(name: "DM")
      Entry.create(user_id: current_user.id, chat_room_id: chat_room.id)
      Entry.create(user_id: params[:user_id], chat_room_id: chat_room.id)
    end
    User.find(params[:user_id]).create_notification_follow(current_user)
    redirect_to request.referer
  end
end
```

**Comment by iijima-yuri** [comment]
アドバイスありがとうございます！
上記2点、うまくいきました！
entranceアクションがあんなにシンプルでいいとは思いませんでした、、、。
今度は土屋さんに書いていただいたようにロジックを書き出してみます！
ありがとうございました！

>チャットルームのメッセージの名前がログインしているユーザーの名前と異なってしまう

この点なのですが、どうやらログアウトしたユーザー名がそのまま残ってしまって表示されているようで、リロードすると、現在ログインしているユーザー名になります。
以下の画像は「erico」「writer_1」のチャットルームなのですが、関係ない「eri」、「tanaka」が表示されています。（画面収録できず見づらくてすいません）
[![Image from Gyazo](https://i.gyazo.com/65569e703441db4d2532b8a6d8ab58ff.png)](https://gyazo.com/65569e703441db4d2532b8a6d8ab58ff)

これは、今回変更したコードは関係ないですよね？
Action Cableを利用していますが、その影響なのでしょうか？

質問が多くて申し訳ありません、よろしくお願いします。

**Comment by Tsuchiya2** [comment]
画像だけなのでなんとも言えませんが...行ったことは以下であっていますか？

●ブラウザを更新して表示が名前の部分が正常になる
- AさんとBさんのチャンネルにて、Aさんで投稿
- アカウントを切り替えてBさんでチャットルームに入る
- 表示名が異なる？？ 
- ブラウザを更新すると正しい表示名に直る

上記であれば考えられることとしては、turboを使っていたらそのキャッシュが表示されてしまっている可能性があるかもしれません。

参考：https://zenn.dev/shita1112/books/cat-hotwire-turbo/viewer/turbo-drive の画面遷移時にDOMContentLoadedが発火しない部分

ブラウザを更新して直るのであれば、一旦その部分は後回しにしても良いかと思います（アカウントを切り替えることは無いだろうとの判断から）
