### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [iijima-yuri/DANSYARI#69]
MVPリリースお疲れ様でした。
以下レビューになります。

---

### READMEから課題解決する実装がされているか&動いている
こちら確認しました。LGTMです。

### より良くするための改善案
技術力は一定水準に達しているように感じました。
技術力は現状でも就活に臨んで良いレベルです。
ただUI/UXの部分がマイナスの印象を与えてしまっており、そこの改善を行えば就活に臨んでも大丈夫だと評価しました。（その後の機能の実装は後回しにして、UI/UXの改善を最優先で取り組んでください）

改善を行った方が良いと感じた部分は以下になります。

■品物一覧への導線
現状、品物一覧への導線はトップページから検索を行うかリンクを踏むかでないとアクセスできないため、ログイン後はアイコンをクリックすると該当ページに遷移できるようにした方が良いかと感じました。

その際、トップページにしか検索機能が無いため、品物一覧ページからも検索できるようにしましょう。

■マイページから各動線に流れるフローを修正
現状、マイページに遷移してからでないと、品物の投稿が出来なかったり、チャットへ行けなかったりするので改善を行いましょう。

まず品物の投稿に関しては、品物一覧、ヘッダーから投稿できるようにするのを検討・対応してください。

チャットルームに関しても、マイページからの遷移には違和感を感じました。ヘッダーからチャットできるユーザー一覧ページに遷移して、ユーザーを選択したら、すくにそのユーザーとのチャットルームに遷移してやり取りができるようにしましょう。

メッセージ一覧・ユーザーのページは無くても良いかと思います。
![スクリーンショット 2024-01-17 17 56 14](https://github.com/iijima-yuri/DANSYARI/assets/61481161/d0fbe8f3-886d-4664-ae90-8ce9cf88483b)

![スクリーンショット 2024-01-17 17 55 59](https://github.com/iijima-yuri/DANSYARI/assets/61481161/b3d4a574-a759-47f0-8d5e-4956bbceea95)

■チャットルームでのバグ修正
Say sometingのところに文字列を入力してreturnキーを押すと、入力フォームは空になるものの画面にはそれが表示されず、その状態で新しく入力フォームに値を入れて"送信"ボタンを押すと、先程のreturn操作の数に応じて、投稿した文字列が複数表示されてしまうバグがありました。原因を特定して修正しましょう。

また、何も文字列を入力していない状態で"送信"ボタンを押すと、空状態の投稿が行われてしまうため、そうならないように修正も行いましょう。

■いいね一覧に画像がされていない
品物・思い出の品物一覧では画像が表示されているのに、こちらには表示されないのは違和感がありました。こちらも他と同様に表示されるようにしましょう。

■品物一覧に表示される画像の大きさ指定
投稿された画像によってカードの大きさが変わっているため、表示する画像をリサイズなどして統一しましょう。

■品物カードのタイトルをクリックしないと詳細へ遷移しないのを改善
現状、品物名のところをクリックしないと詳細ページへ遷移しないため、カード内の表示を再構築して画像をクリックしても遷移するような形に修正しましょう。
![スクリーンショット 2024-01-17 18 28 50](https://github.com/iijima-yuri/DANSYARI/assets/61481161/beb02f79-ee0e-4f1c-94d7-788199993b82)

▼以下イメージ▼
画像と商品名をクリックすると詳細ページへ遷移
![スクリーンショット 2024-01-17 18 32 25](https://github.com/iijima-yuri/DANSYARI/assets/61481161/8e291ea3-6fc8-4588-84a5-bd1a42577369)

■他のユーザー詳細ページ
他のユーザーの詳細ページが閲覧できるのを確認した際に、捨てた品物・残した品物・悩み中の品物の件数が表示されているものの、それらを閲覧できないのに違和感を感じました。マイページの同様の表示からは品物を確認できるので、こちらも同様にしましょう。

■チャットできるユーザー一覧（フォローしているユーザー）
・「ユーザー名：」の表記は削ってよいかと思いました。（他の箇所も同様です）
![スクリーンショット 2024-01-17 18 12 07](https://github.com/iijima-yuri/DANSYARI/assets/61481161/479b54bb-6d7a-4983-bdb7-eb9524516b7a)

■品物投稿時に失敗した際
現状、投稿ができなくても、ソレと分かるフラッシュメッセージが無かったりと、ユーザーに失敗と気付ける案内が無いため、フラッシュメッセージなどで分かるようにしてあげましょう。

■投稿フォーム
投稿フォームの入力フォームはplaceholderを設定して、どんあことを入力すれば良いかが分かるようにしておきましょう。

また、画像ファイルが選択されたタイミングで NO PHOTO のところに画像が表示されるようにすると、ちゃんと選択できていることがユーザーに伝わるかと思います。（他の箇所も同様です）

画像が無い場合は投稿できないようにバリデーションを設けると良いかと思いました。理由としては品物一覧にNO PHOTOやデフォルト画像の投稿が散見されてしまうと、サービスの質が高くないように感じてしまいますし、適当な投稿が多くなってしまう要因に繋がってしまうかと考えたためです。

■トップページ
「→すべての品物はこちら」の文言ですが、ブラウザの大きさによっては背景写真と重なってしまって、それが文字列・リンクになっていることに気づけませんでした。

■その他
・ブラウザのコンソールに表示される文字列は検証用であるならば、表示されないように修正しておきましょう。

・READMEは就活向けのものに整えていきましょう。

---

以下対応をお願いします。
- 上記レビューを元にissue化
- 本リリースに向けて取り組む予定のものをissue化

加えて以下のことに関して、コメント欄に具体的な日付を記載いただいて、Mattermostのチャンネルの方に私宛にメンションを付けてご連絡をお願いいたします。
- 上記修正化飲料の目処（具体的な日付）
- 本リリースの目処（具体的な日付）

よろしくお願いいたします。

**Comment by iijima-yuri** [comment]
返信が遅くなり申し訳ありません。

レビューありがとうございました！
ご指摘いたいただいた点をissue化し、スケジュールを立てました。
その中で、私の解釈が合っているか、不安な箇所があったので、確認していただいてもよろしいでしょうか？
あと、Rspecテストを行なっていないのですが、やった方が良いでしょうか？
> ■品物一覧への導線
現状、品物一覧への導線はトップページから検索を行うかリンクを踏むかでないとアクセスできないため、ログイン後はアイコンをクリックすると該当ページに遷移できるようにした方が良いかと感じました。
その際、トップページにしか検索機能が無いため、品物一覧ページからも検索できるようにしましょう。

・ヘッダーに検索バーをつける（この他にヘッダーに追加するリンクがあるので、検索バーだけヘッダーに残し、その他のリンクはハンバーガメニューにする）
・ログイン後、品物一覧ページに遷移するようにする

以上2点のissueを建てたのですが、あってますでしょうか？


以下、たてたissueと具体的なスケジュールになります。
ご指摘いただいた点を加味して、自分で考えて追加したissueもあるので合わせて確認いただければと思います。
なお、 **本リリースは2月8日を予定**しています。

<ご指摘いただいた点>
・ヘッダーに検索バーの追加（1月21日）
・ヘッダーにチャットルームの追加（1月21日）
・ハンバーガーメニューの変更（1月22日）
・品物一覧ページ、ヘッダーに投稿フォームの追加（1月22日）
・ログイン後、品物一覧ページに遷移する様にする（1月23日）
・いいね一覧画面に画像の追加（1月23日）
・投稿画像をクリックすると、詳細ページに遷移するようにする（1月24日）
・投稿の表示の仕方を変更（1月24日）
・他のユーザー詳細ページから、捨てた品物、残した品物、悩み中の品物の表示するようにする（1月24日）
・品物投稿時のフラッシュメッセージ（1月25日）
・投稿フォームの入力フォームにpraceholderの追加（1月25日）
・投稿フォームの画像プレビュー（1月25日）
・投稿フォームの画像にバリデーション付与（1月25日）
・画像の大きさのリサイズ（1月26日）
・「→すべての品物はこちら」の位置調整（1月26日）
・「ユーザー名：」表記の削除（1月26日）
・チャットルームのメッセージ一覧、ユーザーページの削除（1月27日）
・チャットルームでのバグ修正（1月28日）
・ブラウザのコンソール表示の削除（1月28日）
・READMEの最新化（2月6日）

<自分で考えた点>
・meta情報（faviconなど）の追加（1月21日）
・チャットルームからメッセージがあった場合、通知するようにする（1月29日）
・いいね一覧画面、ジャンル検索結果画面、タグ検索結果画面のページネーションの追加（1月23日）
・投稿を非表示にした場合、非公開の投稿がわかるように、マイページのサイドバーにリンク追加（1月30日）
・品物一覧の表示の大きさ統一（1月31日）

・パスワードリセット（2月1日）
・お問い合わせ（〜1月20日）※レビュー前に始めてしまっていたため、先に実装
・Google APIログイン（2月3日）
・管理者画面（2月5日）

お忙しい中、申し訳ありませんがよろしくお願いします。

**Comment by Tsuchiya2** [comment]
ご返信ありがとうございます。
質問に関してまずお答えします。

> Rspecテストを行なっていないのですが、やった方が良いでしょうか？

こちらは後で良いかと。本リリースした後とかに就活と合わせて記載していく感じで、他の実装や修正を優先的に取り組みましょう。

> ・ヘッダーに検索バーをつける（この他にヘッダーに追加するリンクがあるので、検索バーだけヘッダーに残し、その他のリンクはハンバーガメニューにする）
・ログイン後、品物一覧ページに遷移するようにする

こちらは、ログイン後に品物一覧ページに遷移するのはお願いしたいです。またアイコンを押したら品物一覧ページへ遷移させる形が良いかと思います。（ログインしていない場合はトップページに遷移）

検索に関してはヘッダーでなくても良いです。品物一覧ページの上部に表示される形で良いかと思います。

---

issue・本リリース日時ありがとうございます。
承知しました。引き続き開発頑張ってください！

**Comment by iijima-yuri** [comment]
> こちらは、ログイン後に品物一覧ページに遷移するのはお願いしたいです。またアイコンを押したら品物一覧ページへ遷移させる形が良いかと思います。（ログインしていない場合はトップページに遷移）

了解いたしました！
検索バーは品物一覧ページの上部のみに表示される形にして、アイコン（ヘッダーのアイコンで合ってますか？）を押したら品物一覧ページへ遷移させる形にしたいと思います。
issueも変更しておきます。

ありがとうございました！
